### ISSUE TITLE
Exousia roadmap

### ISSUE THREAD

**Issue by pizzi80** [eclipse-ee4j/exousia#17]
Hi
first of all thanks for the effort to create this project which is 
insanely complex due to the lack of good api from java and servlet 

I've taken a closer look at the code and I saw that is largerly based on jdk SecurityManager & co

I'm forking exousia to try to fix a bug with Tomcat and in case create a PR

Which is the best approach to remove all the dependencies from the
SecurityManager framework that will be removed soon from Java?

Due to this fact a lot of utility methods uses Enumeration instead of Collection
whit a lot of data structure conversions which are not optimal for performance

IMHO this project should be fused with Soteria

... Everyone at some point needs an authentication with user's roles

my 2 cents ;)

**Comment by pizzi80** [comment]
> Yes and no ;)
> Yes, the types from the JDK SecurityManager & Co are used (Policy, Subject Principal, Permission, ...).
> But, in a way, no, since essentially the Policy is only used as an entry into the "authorization module" itself, e.g. about everything is channeled through one of the check permission methods, like this one:

Yes, exactly what i thought, basically you used the "concept" and the model but Overridden everything 
to be used for a real use case with user/groups/roles ... 
 
> https://github.com/eclipse-ee4j/exousia/blob/master/impl/src/main/java/org/glassfish/exousia/AuthorizationService.java#L555
> 
> Now we conceptually don't necessarily need to use `policy.implies` at all. I always thought it was a mismatch to use Policy for the permission checks anyway, as it mixed code bases checks with principal based checks, which are totally different.
> Essentially we need a replacement for Policy. The plan was to do it for EE 10, but unfortunately nobody picked up the work for it.

I understand the philosophy behind because if someone @ java created it, 
it's correct that you use what java offers ... but now they removed everything so,
at the moment we could copy some classes from actual java implementation 
and then make a refactor to simplify everything

the main problem is always the same: Java and Servlet need to be improved to simplify the developer life

> Soteria, Exousia and a third project (not yet at Eclipse) called [Eleos](https://github.com/omnifaces/eleos) work together.

:face_with_spiral_eyes: 

I hope that at some point ( JakartaEE 11 ?) 
I could add a single dependency on maven and all the auth's job it's done :crossed_fingers:

**Comment by pizzi80** [comment]
thanks for the explanation :top:  ;)

**Comment by arjantijms** [comment]
Yes, Exousia is still needed. The version is 2.1.0, which aligns with Jakarta Authorization 2.1 and Jakarta EE 10.
